spring:
  ssl:
    bundle:
      jks:
        "server":
          reload-on-update: false
          keystore:
            location: "classpath:secret/secret-box.bcfks"
            password: "123456"
            type: "BCFKS"
            provider: "BC"
          key:
            alias: "tomcat-ssl"
      pem:
        "client":
          reload-on-update: false
          truststore:
            certificate: "classpath:secret/tomcat-ssl-cert.pem"
