# ----------------------------------------------------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------------------------------------------------
spring:
  application:
    name: "@APP_NAME@"
    version: "@APP_VERSION@"
  profiles:
    active:
      - "dev"
    include:
      - "ssl"
  autoconfigure:
    exclude:
      - "org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration"
server:
  ssl:
    enabled: true
    bundle: "server"
  port: 8443

# ----------------------------------------------------------------------------------------------------------------------
# Actuator
# ----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    env:
      show-values: always
    shutdown:
      access: none
  info:
    env:
      enabled: false
    git:
      enabled: true
      mode: simple
    build:
      enabled: false
    os:
      enabled: false
    java:
      enabled: false
    ssl:
      enabled: false
    process:
      enabled: true
    defaults:
      enabled: true
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: [ "health", "info", "metrics", "env", "beans", "securityproviders" ]
info:
  { }
